export const ActionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCTS : "SELECTED_PRODUCTS",
    REMOVE_SELECTED_PRODUCTS : "REMOVE_SELECTED_PRODUCTS",
    ADD_PRODUCT_TO_CART:"ADD_PRODUCT_TO_CART",
    EDIT_CART_PRODUCT:"EDIT_CART_PRODUCT",
    REMOVE_PRODUCT_FROM_CART:"REMOVE_PRODUCT_FROM_CART"
};
